from __future__ import annotations

import asyncio
import logging

from app.core.config import get_settings
from app.gateway.hermes_gateway import HermesGateway
from app.models.task import TaskStatus
from app.storage import store

logger = logging.getLogger(__name__)


class PlanningWorker:
    def __init__(self, gateway: HermesGateway):
        self._gateway = gateway

    async def tick(self) -> None:
        tasks = await store.list_by_status(TaskStatus.NEW.value)
        if not tasks:
            return

        logger.info("planning worker found %d new tasks", len(tasks))

        for task in tasks:
            task_id = task["id"]
            try:
                result = await self._gateway.submit_plan(
                    task_id=task_id,
                    context=task.get("title", ""),
                )

                plan_id = await store.add_plan(
                    task_id=task_id,
                    plan_text=result.get("plan_text", ""),
                    risk_summary=result.get("risk_summary", ""),
                    expected_outputs=result.get("expected_outputs", ""),
                )
                await store.update_task(task_id, status=TaskStatus.PENDING_APPROVAL.value, current_plan_id=plan_id)
                await store.add_event(task_id, "plan_generated", f"plan {plan_id} generated by hermes")
                logger.info("planning worker completed task %s -> PendingApproval", task_id)
            except Exception:
                logger.exception("planning worker failed for task %s", task_id)
                await store.update_task(task_id, status=TaskStatus.FAILED.value)
                await store.add_event(task_id, "plan_failed", "hermes plan generation failed")


class ExecutionWorker:
    def __init__(self, gateway: HermesGateway):
        self._gateway = gateway

    async def tick(self) -> None:
        tasks = await store.list_by_status(TaskStatus.APPROVED.value, limit=1)
        if not tasks:
            return

        task = tasks[0]
        task_id = task["id"]
        plan_id = task.get("approved_plan_id") or task.get("current_plan_id")

        plan_snapshot = {"plan_text": ""}
        if plan_id:
            plan = await store.get_plan(plan_id)
            if plan:
                plan_snapshot = {"plan_text": plan.get("plan_text", "")}

        await store.update_task(task_id, status=TaskStatus.EXECUTING.value)
        await store.add_event(task_id, "execution_started", "submitted to hermes for execution")
        logger.info("execution worker started task %s", task_id)

        try:
            result = await self._gateway.submit_execution(
                task_id=task_id,
                approved_plan_snapshot=plan_snapshot,
            )

            status = result.get("status", "succeeded")
            summary = result.get("result_summary", "")

            if status == "succeeded":
                await store.update_task(task_id, status=TaskStatus.SUCCEEDED.value)
            else:
                await store.update_task(task_id, status=TaskStatus.FAILED.value)

            await store.add_event(task_id, "execution_completed", f"status={status}, summary={summary[:200]}")
            logger.info("execution worker completed task %s -> %s", task_id, status)
        except Exception:
            logger.exception("execution worker failed for task %s", task_id)
            await store.update_task(task_id, status=TaskStatus.FAILED.value)
            await store.add_event(task_id, "execution_failed", "hermes execution failed")


async def worker_loop():
    settings = get_settings()
    gateway = HermesGateway()
    planning = PlanningWorker(gateway)
    execution = ExecutionWorker(gateway)
    interval = settings.worker_interval

    logger.info("worker loop started, interval=%ds", interval)

    while True:
        try:
            await planning.tick()
            await execution.tick()
        except Exception:
            logger.exception("worker loop error")

        await asyncio.sleep(interval)
